### ISSUE TITLE
[ISSUE] Issue with `databricks_storage_credential` resource for Azure Databricks

### ISSUE THREAD

**Issue by kingnathanal** [databricks/terraform-provider-databricks#3022]
### Configuration

```hcl
provider "databricks" {
  host = var.global_databricks_workspace_url
}

resource "databricks_storage_credential" "this" {
  name  = "a${var.asms_number}-${module.tagging.environment_label}-musea2-${var.scope}-sc-dbxac"
  owner = var.platform_ad_group_name
  azure_managed_identity {
    access_connector_id = azurerm_databricks_access_connector.this.id
    managed_identity_id = azurerm_user_assigned_identity.databricks.id
  }
  comment = "storage cred managed identity credential managed by TF"
}

resource "databricks_grants" "external_creds" {
  storage_credential = databricks_storage_credential.this.id
  grant {
    principal  = var.privileged_ad_group_name
    privileges = ["ALL PRIVILEGES"]
  }
}

resource "databricks_cluster" "unity_shared" {
  cluster_name            = "a${var.asms_number}-${var.scope}-shared-cluster"
  spark_version           = data.databricks_spark_version.latest.id
  node_type_id            = data.databricks_node_type.this.id
  autotermination_minutes = 60
  autoscale {
    min_workers = 1
    max_workers = 2
  }
  azure_attributes {
    availability = "ON_DEMAND_AZURE"
  }
  data_security_mode = "USER_ISOLATION"
}
```

### Expected Behavior
Should be able to create storage credential resource using Service Principal

### Actual Behavior
Terraform fails during apply with an error:
```
│ Error: cannot create storage credential: Refresh token not found for userId: Some(586502210709458)
│ 
│   with databricks_storage_credential.this,
│   on main.tf line 263, in resource "databricks_storage_credential" "this":
│  263: resource "databricks_storage_credential" "this" {
│ 
╵
```

### Terraform and provider versions

```
Terraform version 1.3.7
databricks = {
      source  = "databricks/databricks"
      version = "1.30.0"
    }
```

### Is it a regression?

Have not tried this with any other version

### Debug Output

```
databricks_storage_credential.this: Creating...
2023-12-12T02:41:03.548Z [DEBUG] databricks_storage_credential.this: applying the planned Create change
2023-12-12T02:41:03.550Z [DEBUG] provider.terraform-provider-databricks_v1.30.0: setting computed for "databricks_gcp_service_account" from ComputedKeys: timestamp=2023-12-12T02:41:03.550Z
2023-12-12T02:41:04.150Z [DEBUG] provider.terraform-provider-databricks_v1.30.0: non-retriable error: Refresh token not found for userId: Some(586502210709458): @module=databricks tf_req_id=94e43f13-cef1-ae67-5087-6e6419683cd6 tf_rpc=ApplyResourceChange tf_provider_addr=registry.terraform.io/databricks/databricks tf_resource_type=databricks_storage_credential @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/logger/logger.go:33 timestamp=2023-12-12T02:41:04.150Z
2023-12-12T02:41:04.151Z [DEBUG] provider.terraform-provider-databricks_v1.30.0: POST /api/2.1/unity-catalog/storage-credentials
> {
>   "azure_managed_identity": {
>     "access_connector_id": "/subscriptions/80d4a2fc-1764-4d22-819e-6d2109be33fb/resourceGroups/a219315-dt9-musea2-rg-ocrm/pr... (85 more bytes)",
>     "managed_identity_id": "/subscriptions/80d4a2fc-1764-4d22-819e-6d2109be33fb/resourceGroups/a219315-dt9-musea2-rg-ocrm/pr... (94 more bytes)"
>   },
>   "comment": "storage cred managed identity credential managed by TF",
>   "name": "a219315-dt9-musea2-ocrm-sc-dbxac"
> }
< HTTP/2.0 404 Not Found
< {
<   "details": [
<     {
<       "@type": "type.googleapis.com/google.rpc.RequestInfo",
<       "request_id": "0b7ab091-92ef-4b33-93df-ae25faf67616",
<       "serving_data": ""
<     }
<   ],
<   "error_code": "RESOURCE_DOES_NOT_EXIST",
<   "message": "Refresh token not found for userId: Some(586502210709458)"
< }: @module=databricks tf_provider_addr=registry.terraform.io/databricks/databricks tf_req_id=94e43f13-cef1-ae67-5087-6e6419683cd6 @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/logger/logger.go:33 tf_resource_type=databricks_storage_credential tf_rpc=ApplyResourceChange timestamp=2023-12-12T02:41:04.150Z
2023-12-12T02:41:04.151Z [ERROR] provider.terraform-provider-databricks_v1.30.0: Response contains error diagnostic: diagnostic_severity=ERROR diagnostic_summary="cannot create storage credential: Refresh token not found for userId: Some(586502210709458)" tf_provider_addr=registry.terraform.io/databricks/databricks @module=sdk.proto diagnostic_detail= tf_proto_version=5.4 tf_req_id=94e43f13-cef1-ae67-5087-6e6419683cd6 tf_resource_type=databricks_storage_credential @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/diag/diagnostics.go:58 tf_rpc=ApplyResourceChange timestamp=2023-12-12T02:41:04.151Z
2023-12-12T02:41:04.152Z [ERROR] vertex "databricks_storage_credential.this" error: cannot create storage credential: Refresh token not found for userId: Some(586502210709458)
2023-12-12T02:41:04.319Z [INFO]  Starting apply for module.domain_analytics_nsg.azurerm_network_security_group.this
module.domain_analytics_nsg.azurerm_network_security_group.this:
```

### Important Factoids

My Terraform is normally applied using a Service Principal, but when I change the Databricks provider to use a PAT like below:
```hcl
provider "databricks" {
  host = var.global_databricks_workspace_url
  token     = "################################"
  auth_type = "pat"
}
```
I am able to create the storage credential no issues. 

I am also able to create other Databricks resources like the Compute Cluster with just the Service Principal also, shown in the configuration above.  

The error makes this hard to know if this is a permission issue or an issue with the provider

**Comment by hargut** [comment]
Seeing the same error with databricks cli and a service principal in use on an Azure env.

**Comment by kingnathanal** [comment]
@hargut Thanks I dont feel crazy anymore. Did this work for you before? Thinking of rolling back to a earlier provider version just to see if it works but it its a little shooting darts to know which version to use.

**Comment by hargut** [comment]
@kingnathanal 
Sorry, I've no idea about that as I've not used it like that before. I've also opened a ticket on the cli repo.

Creation with a user token as well works fine with the cli, so it seems to be specific for the service principal.

**Comment by mgyucht** [comment]
This is likely an issue with the backing service. I'll raise this issue to the underlying team to see if they can take a look.

**Comment by hargut** [comment]
Thanks for having a closer look. :+1:

**Comment by kingnathanal** [comment]
@mgyucht Any updates on this? Thanks

**Comment by hargut** [comment]
https://github.com/databricks/cli/issues/1108#issuecomment-1905946370

**Comment by wschultz-boxboat** [comment]
Receiving the same error with Terraform 1.6.6 and databricks/databricks 1.36.1

**Comment by wschultz-boxboat** [comment]
Given the inclusion of a data resource for storage_credential being added to 1.37.0, I decided to give azurerm_storage_credential another try on 1.37.0, and it still fails with the same error. Terraform 1.6.6

**Comment by antsok** [comment]
Are there updates on the fix for this issue ?

**Comment by GavWall** [comment]
I can confirm the issue still occurs with version 1.53.0 of the databricks terraform provider, with the workaround of requiring the Managed Identity to be granted Account Admin rights (which is exactly what we'd like to avoid - the MI/SP was already a metastore owner, which should have been enough in our scenario).

**Comment by alexott** [comment]
@GavWall @antsok it's an UC backend restriction, not the Terraform one - open the support ticket against UC API to solve it.

**Comment by antsok** [comment]
@alexott I wonder if the support will want to look at the ticket if it is created since the case is documented as unsupported. https://learn.microsoft.com/en-us/azure/databricks/connect/unity-catalog/storage-credentials

**Comment by alexott** [comment]
My point is that it's not a terraform issue...

**Comment by zaher-mh** [comment]
Hi all ! This still an issue for us, even though [December's release ](https://learn.microsoft.com/en-us/azure/databricks/release-notes/product/2024/december#delegate-the-ability-to-create-a-storage-credential-in-unity-catalog-to-a-service-principal) for the platform added delegation to service principals. The [documentation](https://learn.microsoft.com/en-us/azure/databricks/connect/unity-catalog/cloud-storage/storage-credentials) doesn't explain the impacts but the section stating that SP has to be an Account Admin disappeared. Was any one able to test it ?

**Comment by daniel-jimenezgarcia-ow** [comment]
Just came across this issue, I can confirm it still is an issue with latest provider 1.64.1, even though it should work as per https://github.com/databricks/terraform-provider-databricks/issues/2828#issuecomment-2551503882 and [December 2024 release notes](https://learn.microsoft.com/en-us/azure/databricks/release-notes/product/2024/december#delegate-the-ability-to-create-a-storage-credential-in-unity-catalog-to-a-service-principal)

I have assigned the `CREATE STORAGE CREDENTIAL` to both a service principal and my user (none of which is a databricks account admin). 
- With a PAT for my user, I can create a storage credential. 
- The same code using the service principal (tried authenticating using both client-secret and a service principal's PAT) fails with the same `Error: cannot create storage credential: Refresh token not found for userId`.

For additional context, delegating permissions was the approach recommended by databricks for a federated model where teams could create their own catalogs/storage without requiring admin access to the entire databricks account. 
Given our infrastructure setup is automated with terraform running as service principals, the issue effectively blocks our adoption of the unity catalog.

**Comment by alexott** [comment]
it's not a Terraform problem. Try with AAD authentication for service principal, not with PAT...

**Comment by daniel-jimenezgarcia-ow** [comment]
> it's not a Terraform problem. Try with AAD authentication for service principal, not with PAT...

Thanks @alexott, I get the same issue when authenticating the service principal using the azure-client-secret auth type. 
(I just tried using a PAT for the service principal just in case. The description suggested PAT as a workaround and it wasnt entirely clear if it was a PAT for a personal account or a PAT for the principal, so was worth a shot)

**Comment by wenesak** [comment]
I just encounter this issue today, I hope it gets fixed promptly

**Comment by mixam24** [comment]
@alexott I agree that it is not a terraform provider nor the databricks-sdk-go problem as I reproduced the bug described by @daniel-jimenezgarcia-ow in the following setups:
- Using terraform provider with `auth_type = "pat"` setting of the provider and generated EntraID token for SP as follows:
   ```
   export DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq .accessToken -r)
   ```
-  Using terraform provider with `auth_type = "azure-client-secret"` setting of the provider and set `ARM_CLIENT_ID`, `ARM_CLIENT_SECRET`, and `ARM_TENANT_ID`
- Using curl with generated EntraID token as the Bearer token.

All three options produce identical error messages in the backend service. Here is a sample diagnostic log message:
```
{
  "records": [
    {
      "resourceId": "/SUBSCRIPTIONS/11111111-2F40-4CEA-B300-222222222222/RESOURCEGROUPS/RESOURCE_GROUP/PROVIDERS/MICROSOFT.DATABRICKS/WORKSPACES/DATABRICKS-DEV",
      "operationVersion": "1.0.0",
      "identity": "{\"email\":\"22222222-f0e9-4c89-ac40-111111111111\",\"subjectName\":null}",
      "operationName": "Microsoft.Databricks/unityCatalog/getPermissions",
      "time": "2025-02-17T17:47:52Z",
      "category": "unityCatalog",
      "properties": {
        "sourceIPAddress": "11.222.333.111",
        "logId": "00000000-1111-2222-4444-111111111111",
        "serviceName": "unityCatalog",
        "userAgent": "databricks-tf-provider/1.65.0 databricks-sdk-go/0.57.0 go/1.22.5 os/darwin terraform/1.10.5 sdk/sdkv2 resource/grants auth/azure-client-secret",
        "response": "{\"statusCode\":200,\"result\":\"{}\"}",
        "sessionId": null,
        "actionName": "getPermissions",
        "requestId": "66666666-5555-4444-3333-222222222222",
        "requestParams": "{\"securable_type\":\"STORAGE_CREDENTIAL\",\"securable_full_name\":\"existing_storage_credential\",\"workspace_id\":\"9999999999999999\",\"metastore_id\":\"99999999-3333-4444-5555-666666666666\"}"
      },
      "Host": "0217-020432-ooy6wx4h-10-139-108-10"
    },
    {
      "resourceId": "/SUBSCRIPTIONS/11111111-2F40-4CEA-B300-222222222222/RESOURCEGROUPS/RESOURCE_GROUP/PROVIDERS/MICROSOFT.DATABRICKS/WORKSPACES/DATABRICKS-DEV",
      "operationVersion": "1.0.0",
      "identity": "{\"email\":\"22222222-f0e9-4c89-ac40-111111111111\",\"subjectName\":null}",
      "operationName": "Microsoft.Databricks/unityCatalog/createStorageCredential",
      "time": "2025-02-17T17:47:54Z",
      "category": "unityCatalog",
      "properties": {
        "sourceIPAddress": "11.222.333.111",
        "logId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
        "serviceName": "unityCatalog",
        "userAgent": "databricks-tf-provider/1.65.0 databricks-sdk-go/0.57.0 go/1.22.5 os/darwin terraform/1.10.5 sdk/sdkv2 resource/storage_credential auth/azure-client-secret",
        "response": "{\"statusCode\":404,\"errorMessage\":\"DatabricksServiceException: RESOURCE_DOES_NOT_EXIST: Refresh token not found for userId: Some(7777777777777777)\"}",
        "sessionId": null,
        "actionName": "createStorageCredential",
        "requestId": "11111111-2222-3333-4444-555555555555",
        "requestParams": "{\"name\":\"new_storage_credential\",\"azure_managed_identity\":\"{\\\"access_connector_id\\\":\\\"/subscriptions/11111111-2F40-4CEA-B300-222222222222/resourceGroups/resource_group/providers/Microsoft.Databricks/accessConnectors/testdev\\\",\\\"managed_identity_id\\\":\\\"/subscriptions/11111111-2F40-4CEA-B300-222222222222/resourceGroups/resource_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testdev\\\"}\",\"comment\":\"Storage credential for test_dev.\",\"workspace_id\":\"9999999999999999\",\"metastore_id\":\"99999999-3333-4444-5555-666666666666\"}"
      },
      "Host": "0217-020432-ooy6wx4h-10-139-108-10"
    }
  ]
}
```

Now the questions are the following: 
-  How should we contact the backend team to make them aware of the issue?
- Could someone please provide an estimate regarding the resolution of this issue from the backend side?

My team and I have been waiting for this feature for [over a year](https://github.com/databricks/terraform-provider-databricks/issues/2828#issuecomment-1941215469). We would really like to finally automate our provisioning process 🙂

**Comment by danielkwok72** [comment]
I got the same issue as well and this is blocking me creating the storage credential with Azure SPN which only has workspace admin on the workspace which has unity catalog enabled by default.

**Comment by daniel-jimenezgarcia-ow** [comment]
FYI, databricks team and MS support notified me a few weeks back that the API has been updated and the issue should be solved. 

We have since been able to create storage credentials using a service principal and terraform 🚀

**Comment by alexott** [comment]
@daniel-jimenezgarcia-ow thank you for confirming it!

**Comment by idontcsharply** [comment]
@daniel-jimenezgarcia-ow would you be able to provide any more information on how you got this working? We've been trying to do the same thing. We have a service principal with CREATE STORAGE CREDENTIAL permission for the metastore in a team's repo, and we want to avoid giving it account admin.

We're still getting the 'cannot create storage credential: Refresh token not found' error.

We've updated to the latest terraform databricks provider to no avail. Are there any extra configuration steps or permissions to grant, maybe we need to be on a preview API version or something?

**Comment by daniel-jimenezgarcia-ow** [comment]
> [@daniel-jimenezgarcia-ow](https://github.com/daniel-jimenezgarcia-ow) would you be able to provide any more information on how you got this working? We've been trying to do the same thing. We have a service principal with CREATE STORAGE CREDENTIAL permission for the metastore in a team's repo, and we want to avoid giving it account admin.
> 
> We're still getting the 'cannot create storage credential: Refresh token not found' error.
> 
> We've updated to the latest terraform databricks provider to no avail. Are there any extra configuration steps or permissions to grant, maybe we need to be on a preview API version or something?

I am afraid I didnt do anything special. I was in touch with Microsoft support and our databricks account team, and tried this out after they notified me a new version of the API was rolled out. Its not entirely clear to me how the changes gets rolled out to all workspaces, so its possible it takes some time for them to reach every customer?

If anything, the principal I was using also had CREATE_CATALOG and CREATE_EXTERNAL_LOCATION permissions in addition to CREATE_STORAGE_CREDENTIAL.

But I would contact support tbh

**Comment by ahmed-wajid** [comment]
@idontcsharply  Which region do you face the error in? I can confirm that WestEurope, SouthEastAsia work fine. But EastUS2, still has the same issue and we are trying to work with Microsoft Support to get it fixed

**Comment by idontcsharply** [comment]
> [@idontcsharply](https://github.com/idontcsharply) Which region do you face the error in? I can confirm that WestEurope, SouthEastAsia work fine. But EastUS2, still has the same issue and we are trying to work with Microsoft Support to get it fixed

We're having the issue with UK South.
